name: CI

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  quality:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
      - run: npm install
      - run: npm run lint
      - run: npm run format
      - run: npm run typecheck
      - run: npm run test
      - run: npm run build
      - run: docker build -f apps/web/Dockerfile -t pingpong-web:ci .
      - run: docker build -f apps/realtime/Dockerfile -t pingpong-realtime:ci .
      - run: docker build -f apps/simulator/Dockerfile -t load-generator:ci .
      - name: Install kubeconform
        run: |
          curl -sSL https://github.com/yannh/kubeconform/releases/download/v0.6.7/kubeconform-linux-amd64.tar.gz | tar xz
          sudo mv kubeconform /usr/local/bin/kubeconform
      - uses: imranismail/setup-kustomize@v2
      - run: kustomize build infra/k8s/overlays/dev | kubeconform -summary -ignore-missing-schemas -
